"""empty message

Revision ID: f1d57ae809db
Revises: 7dbfca723361
Create Date: 2019-07-10 16:48:53.408641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d57ae809db'
down_revision = '7dbfca723361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('age', sa.INTEGER(), nullable=True))
    op.add_column('teachers', sa.Column('age', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'age')
    op.drop_column('students', 'age')
    # ### end Alembic commands ###
